# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56165b86064e48463885c50c1755b9ff2be1c484ca14705a02144d861c42964b6e8ec3cb937c0c1930a7acdb39de2e053fa1bb510579c0363849edd21bf373c6

test:
  secret_key_base: bee3d8a8565a82528a9d1ef154b4d32a6f0fd0f93d624ca52873473af5264ec32ac88a08ebe284eb58238af3840f8260a818523d3cd3803f1bb38c4a3e210971

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
